spring:
  profiles:
    active: development

---

spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security
    username: root
    password: igdefault
  jpa:
    hibernate:
      ddl-auto: update